#defaults: &defaults
#  host: 127.0.0.1
#  port: 27017

#development:
#  <<: *defaults
#  database: api_pages_development

#test:
#  <<: *defaults
#  database: api_pages_test

# set these environment variables on your prod server
production:
  uri: mongodb://heroku:247b6edd029a0c41812d0408ebe2c492@flame.mongohq.com:27103/app4987538
#<%= ENV['MONGOHQ_URL'] %>
